// The TriVoKo phase plan as data. Used by phase-docs.js to write
//   1. the Phase Plan document (all phases in one book)
//   2. one checklist document per phase folder (Phase_N_Name\)
// Step "who": C = Claude builds and explains, M = Madhavan types the key logic (Claude guides + reviews),
//             Y = you do it yourself (accounts, approvals, decisions), T = together
module.exports = [
  {
    n: 0, folder: 'Phase_0_Setup', name: 'Setup', time: '3-4 days',
    goal: 'Create the TriVoKo project so that the backend, the frontend and the database all run on your laptop and on GitHub, and agree on the look of the shop before any page is coded.',
    example: 'Before a new shop opens in a mall, the owner gets the keys, puts up the name board, paints the walls in the brand colours and draws where every shelf will go. No goods are sold yet - but everything is ready.',
    steps: [
      ['Y', 'Approve this Phase Plan (or ask for changes)'],
      ['C', 'Turn `03_TriVoKo_Main_Project` into a Git repository: folders `backend/`, `frontend/`, `load-tests/`, `e2e/`, `docs/`, `tools/`; `.gitignore`, `.gitattributes`, README'],
      ['C', 'Spring Boot 4 + Java 25 skeleton, package `com.trivoko`, same versions as EventHub; dev and prod profiles; `.env` (git-ignored) for passwords'],
      ['C', '`docker-compose.yml`: MySQL 8.4 and Mailpit, with new ports (3307, 8026) so EventHub and TriVoKo never clash'],
      ['C', 'Copy the EventHub base: ProblemDetail error handler, `/api/health`, Swagger, base SecurityConfig, Flyway, Testcontainers MySQL for tests'],
      ['C', 'React 19 + Vite skeleton: Tailwind v4 with TriVoKo teal + saffron colour tokens, dark mode, React Router, Redux Toolkit, Axios, Vite proxy; footer shows "Backend: UP"'],
      ['C', 'Copy the EventHub UI kit (Button, Card, Badge, Modal, Loader, FormField, Toaster) and recolour it; `/style-guide` page'],
      ['C', 'TriVoKo logo (SVG) + favicon'],
      ['C', 'GitHub Actions CI: backend build + tests, frontend lint + build + Vitest'],
      ['Y', 'Create the public GitHub repository `trivoko` (or say yes and Claude creates it) and push'],
      ['C', 'Library check (small spikes): Hibernate Search 8, Stripe Java, Cloudinary, OpenPDF and Testcontainers all work with Spring Boot 4 - results written in `docs/decisions.md`'],
      ['C', 'Sketches of the 6 key pages: Home, Search/listing, Product, Cart, Checkout, Seller dashboard'],
      ['C', 'Sample-data plan: 10 categories, 8 sellers, 120 products with variants; where product photos come from'],
      ['Y', 'Approve the sketches and the sample-data plan (or ask for changes)'],
    ],
    output: ['Spring Boot app at localhost:8080 with Swagger', 'React app at localhost:5173 in TriVoKo colours', 'MySQL + Mailpit in Docker', 'GitHub repository `trivoko` with a green CI tick', 'Approved sketches and sample-data plan'],
    done: ['The React page shows "Backend: UP"', '`docker compose up -d` starts MySQL and Mailpit with one command', 'CI is green on GitHub', 'Madhavan has approved the sketches'],
    explain: ['What is a modular monolith, and why did we not choose microservices?', 'Why does the database run in Docker instead of being installed on Windows?', 'What does CI do on every push?'],
    skills: 'Project setup, Maven, npm, Docker, environment variables, CI/CD, design tokens',
    where: '`backend\\`, `frontend\\`, `docker-compose.yml`, `.github\\workflows\\`, `docs\\`',
  },
  {
    n: 1, folder: 'Phase_1_Catalogue_API', name: 'Catalogue API', time: '1 week',
    goal: 'Products exist in the database and anyone can browse them through the API: categories, filters, sorting, paging and product details.',
    example: 'The shelves are filled and every product has a price tag and a label. Customers can walk the aisles, but the billing counter is not open yet.',
    steps: [
      ['C', 'Flyway V1: `categories` (tree with parent), `sellers` (shop name, slug, city, status), `products` (status DRAFT / PENDING / ACTIVE / REJECTED / BLOCKED), `product_variants` (size, colour, price, MRP, stock, version), `product_images`, `price_history`'],
      ['C', 'Flyway V2 seed data from the sample-data plan: 10 categories, 8 sellers, 120 products with variants and photos'],
      ['C', 'Entities and repositories in modules `catalog` and `seller`; money as `BigDecimal` / `DECIMAL(12,2)`'],
      ['C', 'ArchUnit test for the module rule (a module may call another module\'s service, never its repository) - runs in CI from now on'],
      ['C', 'DTO records + mapper; shared `PageResponse`'],
      ['C', '`GET /api/products` with filters (category incl. sub-categories, brand, min/max price, in stock), sort (price, newest) and paging (max 48)'],
      ['C', '`GET /api/products/{slug}` (variants, images, seller), `GET /api/categories` (tree), `GET /api/sellers/{slug}` (shop page)'],
      ['C', 'Price-change service method that always writes `price_history` (used by price alerts in Phase 9)'],
      ['Y', 'Create a free Cloudinary account and put the 3 keys in `.env`'],
      ['C', 'Cloudinary signed upload: `POST /api/uploads/signature` (images only, max 5 MB) - tried with one real photo'],
      ['C', 'Tests: repository tests, service rules, every endpoint (Testcontainers MySQL)'],
      ['C', 'Postman collection with checks, run with newman'],
    ],
    output: ['Catalogue REST API in Swagger', '120 sample products in MySQL', 'Postman collection', 'ArchUnit module rule in CI'],
    done: ['`GET /api/products?category=phones&sort=price` returns the correct pages', 'All Postman checks pass', 'CI green'],
    explain: ['Why does stock live on the variant and not on the product?', 'What is a Flyway migration and why do we never change the database by hand?', 'How do filters become one SQL query (Specifications)?'],
    skills: 'JPA entities, relationships, Flyway, Specifications, paging, DTOs, testing with Testcontainers',
    where: '`backend\\src\\main\\java\\com\\trivoko\\catalog`, `...\\seller`, `db\\migration`, `postman\\`',
  },
  {
    n: 2, folder: 'Phase_2_Accounts_and_Roles', name: 'Accounts & roles', time: '1 week',
    goal: 'Safe login for customers, sellers and admins; a customer can apply to become a seller; a seller can only touch their own products.',
    example: 'Every person in the mall gets the right card: shoppers can enter the shop floor, shopkeepers can enter only their own storeroom, and the mall office can open every door.',
    steps: [
      ['C', 'Flyway: `users`, `user_roles`, `addresses`; `sellers.user_id`; seller status PENDING / APPROVED / REJECTED / BLOCKED'],
      ['C', 'Copy EventHub auth: JWT in httpOnly cookie, CSRF double-submit, BCrypt, 5 wrong logins = 15-minute lock; `/api/auth/register`, `/login`, `/logout`, `/me`'],
      ['C', 'Roles CUSTOMER / SELLER / ADMIN; every new account is a CUSTOMER'],
      ['C', 'Addresses API (max 5, one default)'],
      ['C', '"Become a seller": `POST /api/seller/apply` (shop name, city, optional GST) → PENDING; admin approve / reject endpoints (the admin pages come in Phase 6)'],
      ['C', 'Seller products API: create (DRAFT), edit, submit for approval; `SellerAccess` bean checks ownership on every call'],
      ['C', 'Audit log table + service (who changed what and when)'],
      ['C', 'Dev demo accounts (admin, customers Ravi and Kavya, sellers Chennai Mobiles and Kovai Sports) with the password from `.env`'],
      ['C', 'Tests: Seller A cannot read or edit Seller B\'s product (403/404), unapproved seller cannot sell, login lock, CSRF'],
    ],
    output: ['Working register / login / logout with cookies', 'Seller application and approval API', 'Ownership checks with tests'],
    done: ['A test proves a seller cannot touch another seller\'s product (403)', 'An unapproved seller cannot create products', 'CI green'],
    explain: ['Why is the JWT in an httpOnly cookie and not in localStorage?', 'What does the CSRF token protect against?', 'How does the server know a product belongs to the logged-in seller?'],
    skills: 'Spring Security, JWT, cookies, CSRF, method security, ownership checks',
    where: '`backend\\...\\user`, `...\\auth`, `...\\seller`, `...\\admin`',
  },
  {
    n: 3, folder: 'Phase_3_Shop_Frontend', name: 'Shop frontend', time: '1.5 weeks',
    goal: 'A customer can browse, search the catalogue, choose a size or colour and fill a cart from many sellers - on laptop and phone, light and dark. No payment yet.',
    example: 'The shop doors open and people can walk around and fill their trolleys. The billing counter still has a "coming soon" board.',
    steps: [
      ['C', 'Layout: navbar (search box, category menu, cart count, account menu), footer, mobile menu, Toaster'],
      ['C', 'Home: deals, category tiles, new arrivals, flash-sale banner place'],
      ['C', 'Listing page: filters and sort kept in the URL, pagination, product cards, skeleton loaders, empty state'],
      ['C', 'Product page: photo gallery, variant picker (sold-out sizes disabled), price + MRP + % off, seller box, add to cart'],
      ['C', 'Seller shop page'],
      ['C', 'Cart backend: `carts`, `cart_items`; `GET/PUT/DELETE /api/cart/items`, `POST /api/cart/merge` (quantity capped by stock, max 10)'],
      ['C', 'Cart frontend: guest cart in localStorage + Redux; cart page grouped by seller with the shipping rule; merge after login'],
      ['C', 'Login, Register, Become-a-seller pages; route guards (copied from EventHub)'],
      ['C', 'Addresses page'],
      ['C', 'Vitest: cart maths, URL filters'],
      ['C', 'Automated phone (375 px) + dark-mode scan of every page; fix what it finds'],
    ],
    output: ['The shop website on real API data', 'Cart that survives login', 'Every page works on phone and in dark mode'],
    done: ['A guest adds 3 items from 2 sellers, logs in, and the cart is kept', 'Every page passes the phone + dark-mode check'],
    explain: ['Why are filters kept in the URL?', 'What happens to the guest cart when you log in?', 'Why does the server recalculate prices even though the cart shows them?'],
    skills: 'React components, React Router, Redux Toolkit, forms, responsive Tailwind, localStorage',
    where: '`frontend\\src\\pages`, `...\\components`, `...\\store`; `backend\\...\\cart`',
  },
  {
    n: 4, folder: 'Phase_4_Checkout_and_Payments', name: 'Checkout & payments', time: '2 weeks',
    goal: 'One cart, one Stripe payment, one order split into one package per seller - with stock held safely, coupons, emails and a PDF invoice.',
    example: 'At a food court you pay once at the main counter, and your token is sent to the dosa stall and the juice stall separately. Each stall only sees its own part of your order.',
    steps: [
      ['C', 'Flyway: `orders`, `packages`, `order_items` (copy title, variant and price), `payments`, `processed_payment_events`, `coupons`, `coupon_redemptions`'],
      ['C', '`Money` helpers (rupees ↔ paise, rounding) with unit tests'],
      ['C', 'Coupon rules: flat or %, minimum order, expiry, one use per customer; admin create endpoint'],
      ['M', '★ You type the ORDER SPLIT: group cart lines by seller into packages, shipping fee per package (free above ₹499, else ₹40), coupon share per item (by price, rounding remainder on the last item)'],
      ['M', '★ You write at least one test for the order split (2 sellers + coupon → exact amounts)'],
      ['C', 'CheckoutService: recheck products, sellers, coupon and prices; hold stock with `UPDATE ... SET stock = stock - :qty WHERE stock >= :qty`; roll back and name the item that ran out'],
      ['C', 'Copy the EventHub PaymentGateway switch (Fake when no Stripe key, Stripe Checkout when set)'],
      ['C', 'Stripe webhook (signature check) + "verify on return" fallback + idempotency → order PAID, packages PLACED, coupon used, cart emptied'],
      ['C', 'Expiry job: unpaid after 10 minutes → EXPIRED, stock back; late payment re-takes stock or is refunded automatically'],
      ['C', '`notify` module (copy from EventHub): bell + emails after commit with retry; order email to customer, new-package email to each seller'],
      ['C', 'PDF invoice with OpenPDF: `GET /api/orders/{number}/invoice.pdf`'],
      ['C', 'Frontend: checkout page (address, coupon, summary per package, "price changed" notice), payment result, My orders, order detail'],
      ['C', 'Concurrency test: 100 threads try to buy 10 units → exactly 10 orders'],
      ['Y', 'Create the Stripe test account, put `sk_test` in `.env`, install the Stripe CLI'],
      ['T', 'Real Stripe test: pay with 4242 4242 4242 4242 and receive a real signed webhook (the EventHub to-do)'],
    ],
    output: ['Working checkout with Stripe test mode', 'Split orders with packages per seller', 'Order emails in Mailpit and PDF invoices', 'Your own OrderSplitter class + test'],
    done: ['Pay once for items from 2 sellers → 2 packages PLACED', 'The 100-thread stock test passes', 'A real Stripe 4242 payment confirmed by a signed webhook'],
    explain: ['Walk through checkout from "Place order" to "PLACED" - which table changes at each step?', 'How is the coupon shared between packages, and why store it on each item?', 'Why can a webhook arrive twice, and what stops a double order?'],
    skills: 'Transactions, atomic SQL updates, money maths, Stripe Checkout, webhooks, idempotency, scheduled jobs, PDF',
    where: '`backend\\...\\order`, `...\\payment`, `...\\coupon`, `...\\notify`; checkout pages in `frontend`',
  },
  {
    n: 5, folder: 'Phase_5_Seller_Dashboard', name: 'Seller dashboard', time: '1.5 weeks',
    goal: 'Sellers run their own shop: add products with photos, ship their packages, and see what they earn.',
    example: 'Each shopkeeper gets their own back office: a stock register, a packing table, and an account book that says how much the mall owes them.',
    steps: [
      ['C', 'Seller layout + dashboard: today\'s packages, low stock, earnings, products waiting for approval'],
      ['C', 'Products list + product editor: variants table, photo upload to Cloudinary (drag to reorder, max 8, 5 MB), submit for approval; price change writes `price_history`'],
      ['C', 'Low-stock warnings (default below 5)'],
      ['C', '`PackageStatus` enum with `allowedNext()` + `@Version`; Packed → Shipped (tracking number) → Delivered (demo button)'],
      ['C', 'Cancel before shipping (customer or seller): refund that package, stock back; race test cancel-vs-ship → one wins, other gets 409'],
      ['C', '`seller_ledger`: DELIVERED adds +90%; earnings page with the ledger lines'],
      ['C', 'Customer order detail: tracking timeline per package; email + bell at every step'],
      ['C', 'Sales charts for 7 / 30 / 90 days (Recharts, cached)'],
      ['C', 'Tests: ownership, every package move, ledger amounts'],
    ],
    output: ['Seller back office', 'Package tracking timelines', 'Earnings ledger and sales charts'],
    done: ['A seller ships a package and the customer sees the timeline update', 'Cancel-vs-ship race test passes'],
    explain: ['What is a state machine and why use `allowedNext()`?', 'What does `@Version` do when two people change the same package?', 'Why is the seller balance the sum of ledger lines instead of one number?'],
    skills: 'State machines, optimistic locking, file upload, charts, caching',
    where: '`frontend\\src\\pages\\seller`, `backend\\...\\order`, `...\\seller`',
  },
  {
    n: 6, folder: 'Phase_6_Admin_Panel', name: 'Admin panel', time: '1 week',
    goal: 'The admin controls the marketplace: approves sellers and products, blocks bad actors, creates coupons and reads reports.',
    example: 'The mall office: it decides which shops may open, can close a shop that cheats customers, prints discount coupons and reads the daily sales register.',
    steps: [
      ['C', 'Admin layout + overview cards'],
      ['C', 'Seller approvals (approve / reject with reason, email to the seller)'],
      ['C', 'Product approvals (approve / reject with reason)'],
      ['C', 'Search users, sellers and orders with paging'],
      ['C', 'Block a seller → their products disappear from the shop; block a user → they cannot log in'],
      ['C', 'Coupons page (create, edit, end)'],
      ['C', 'Reports: sales per day, top products, top sellers, return rate (filled in Phase 8)'],
      ['C', 'Activity log page from the audit log'],
      ['C', 'Tests for every admin action and that non-admins get 403'],
    ],
    output: ['Admin panel with approvals, users, coupons, reports, activity log'],
    done: ['Admin blocks a seller → their products disappear from the shop', 'CI green'],
    explain: ['How is "blocked" applied to every shop query without forgetting one?', 'What is written to the audit log and why?'],
    skills: 'Role-based pages, reporting queries (GROUP BY), audit trails',
    where: '`frontend\\src\\pages\\admin`, `backend\\...\\admin`, `...\\analytics`',
  },
  {
    n: 7, folder: 'Phase_7_Flash_Sale', name: 'Flash sale', time: '1.5 weeks',
    goal: 'Standout #1: a flash sale where thousands click at once, exactly the right number win, and stock never goes below zero - proven with a 5,000-user load test.',
    example: 'A big sale at a shop with 100 TVs and 5,000 people at the door. A guard gives out exactly 100 tokens, one per person. Token 101 does not exist.',
    steps: [
      ['C', 'Flyway: `flash_sales`, `flash_sale_items`, `flash_sale_claims` with UNIQUE(sale item, customer)'],
      ['C', 'Admin schedules a sale; sellers offer a variant with sale price + quantity; the quantity is taken out of normal stock'],
      ['M', '★ You type the CLAIM: one atomic `UPDATE ... SET sold = sold + 1 WHERE sold < quantity AND NOW() BETWEEN start AND end`, the unique claim row, and the 10-minute hold at the sale price'],
      ['M', '★ You type the GIVE-BACK: an unpaid claim returns its unit (`sold = sold - 1`)'],
      ['C', 'Sale end: unsold units go back to normal stock'],
      ['C', 'Rate limit on claim per user + IP (429 + Retry-After)'],
      ['C', 'Frontend: home banner countdown (server time), sale page, live "N left" counter, instant "Sold out"'],
      ['M', '★ 1,000 threads / 100 units test - you write the final assertions'],
      ['C', 'k6 load test: 5,000 virtual users against the app in Docker; record requests per second, p95, winners and errors'],
      ['T', 'Decision: if p95 is above 500 ms, try Redis `DECR` and measure again; write the decision with both graphs'],
    ],
    output: ['Flash sale feature with countdown and live counter', 'Your claim + give-back code', 'k6 report and graph in `load-tests\\results`'],
    done: ['k6 report: exactly 100 winners, 0 oversell, 0 errors', 'p95 written in the README'],
    explain: ['Why is "read stock, then write stock" wrong, and why does one UPDATE fix it?', 'What stops one person from winning twice?', 'What did k6 measure, and did we need Redis?'],
    skills: 'Concurrency, atomic SQL, unique constraints, rate limiting, load testing with k6',
    where: '`backend\\...\\flashsale`, `load-tests\\`, flash-sale pages in `frontend`',
  },
  {
    n: 8, folder: 'Phase_8_Returns_and_Refunds', name: 'Returns & refunds', time: '1.5 weeks',
    goal: 'Standout #2: a customer returns one item and gets back exactly the right money through a Stripe partial refund, while stock and the seller ledger stay correct.',
    example: 'You return one shirt from a bill of three. The shop checks it, takes it back to the shelf, and returns only that shirt\'s money - minus its part of the discount you used.',
    steps: [
      ['C', 'Flyway: `return_requests`, `refunds`'],
      ['M', '★ You type the RETURN STATE MACHINE: `ReturnStatus` enum with `allowedNext()` and the service method that moves a return'],
      ['M', '★ You write tests for allowed and illegal moves'],
      ['C', 'Request a return: DELIVERED items only, within 7 days, once per item, reason + optional photo'],
      ['C', 'Seller approve / reject with reason; auto-approve job after 2 days'],
      ['C', 'Escalate once; admin makes the final decision'],
      ['C', 'Picked up → Stripe partial refund of (price × qty − coupon share), one idempotency key per return'],
      ['C', 'Refund done → stock back, minus line in the seller ledger, email + bell'],
      ['C', 'Frontend: return form + timeline (customer), returns page (seller), disputes page (admin); return rate in admin reports'],
      ['C', 'Tests: refund maths, double click = one refund'],
    ],
    output: ['Complete returns flow for 3 roles', 'Stripe partial refunds', 'Your ReturnStatus state machine + tests'],
    done: ['Return one item of a 2-item order → the exact partial refund appears in the Stripe test dashboard', 'Ledger and stock match'],
    explain: ['Draw the return states and say who can make each move', 'How is the refund amount calculated?', 'Why can a refund never happen twice?'],
    skills: 'State machines, Stripe refunds, idempotency, scheduled jobs',
    where: '`backend\\...\\returns`, `...\\payment`, return pages in `frontend`',
  },
  {
    n: 9, folder: 'Phase_9_Reviews_Wishlist_Alerts', name: 'Reviews, wishlist, alerts', time: '1 week',
    goal: 'Standout #3: verified-buyer reviews, a wishlist, and price-drop alerts that are useful and never spammy.',
    example: 'You ask the shopkeeper, "Call me if this TV gets cheaper." He calls once when it does - not five times when he changes the tag five times in a minute.',
    steps: [
      ['C', 'Flyway: `reviews`, `wishlist_items` (price when added, last alerted price)'],
      ['C', 'Reviews only for delivered items, one per item; rating average and star breakdown on the product page'],
      ['C', 'Wishlist API + heart button + wishlist page'],
      ['C', '`PriceChanged` event; alert job every 10 minutes using the latest price; one alert per drop; email + bell'],
      ['C', '"Lowest price in 30 days" on the product page from `price_history`'],
      ['C', 'Tests: 5 price changes in one minute → one alert'],
    ],
    output: ['Reviews, wishlist and price-drop alerts'],
    done: ['Lower a price → a wishlisted customer gets one alert (not five)'],
    explain: ['Why do alerts come from a job every 10 minutes instead of at once?', 'How do we know a reviewer really bought the product?'],
    skills: 'Spring events, scheduled jobs, aggregate queries',
    where: '`backend\\...\\review`, `...\\wishlist`, `...\\notify`',
  },
  {
    n: 10, folder: 'Phase_10_Smart_Search', name: 'Smart search', time: '1 week',
    goal: 'Standout #4: search that forgives typos, suggests while you type, and shows filters with counts.',
    example: 'A good shop assistant understands "iphnoe" means iPhone, and says "we have 12 Samsung and 8 Apple phones" before you ask.',
    steps: [
      ['C', 'Spike: Hibernate Search 8 with the Lucene backend on Spring Boot 4; index folder; rebuild on start'],
      ['C', 'Map products: full-text fields (title, brand, description), keyword fields for facets'],
      ['C', 'Search API: fuzzy match, filters, facets with counts, sort'],
      ['C', 'Suggest API: suggestions after 2 letters'],
      ['C', 'Frontend: search box with suggestions (debounce, keyboard), result page with facet counts'],
      ['C', '"Customers also bought" (SQL, cached 1 hour)'],
      ['T', 'Decision: keep Lucene or fall back to MySQL FULLTEXT for hosting - written in `docs/decisions.md`'],
    ],
    output: ['Smart search with typo tolerance, suggestions and facets'],
    done: ['"iphnoe" finds iPhone', 'Suggestions appear while typing'],
    explain: ['What is an index, and why is search not a SQL LIKE query?', 'How does fuzzy matching find "iphnoe"?'],
    skills: 'Full-text search, Lucene, analyzers, facets, debounce',
    where: '`backend\\...\\search`, search components in `frontend`',
  },
  {
    n: 11, folder: 'Phase_11_Testing_and_Polish', name: 'Testing & polish', time: '1 week',
    goal: 'Portfolio quality: the whole demo story runs as an automated browser test, the code is well covered, safe, fast and pleasant on every screen.',
    example: 'Before the grand opening, an inspector walks through the whole shop as a customer, checks every fire exit, and the cleaners polish every glass door.',
    steps: [
      ['C', 'Playwright end-to-end test of the demo story (buy from 2 sellers, seller ships, customer returns) in CI'],
      ['C', 'JaCoCo coverage about 80% on services; coverage badge'],
      ['C', 'Security review: ownership tests, OWASP checklist, dependency check, secret scan of the Git history'],
      ['C', 'Accessibility (axe), keyboard use, phone + dark mode on every page'],
      ['C', 'Speed: lazy-loaded pages, Cloudinary image sizes; Lighthouse ≥ 90 on Home'],
      ['C', 'Vitest for the main components'],
      ['C', 'README draft'],
    ],
    output: ['E2E tests in CI', 'Coverage report', 'Security and accessibility fixes'],
    done: ['CI green including the E2E test', 'Lighthouse ≥ 90 on the home page'],
    explain: ['What is the difference between a unit, an integration and an end-to-end test?', 'What did the security review find, and how was it fixed?'],
    skills: 'Playwright, coverage, security review, accessibility, performance',
    where: '`e2e\\`, test folders, `README.md`',
  },
  {
    n: 12, folder: 'Phase_12_Launch', name: 'Launch', time: '1 week',
    goal: 'TriVoKo is live on the internet, with demo accounts, a strong README, a demo video and posts that a recruiter can see.',
    example: 'The ribbon is cut, the shop opens to the public, and an advertisement goes into the newspaper.',
    steps: [
      ['Y', 'Choose hosting: free (Render + Aiven + Vercel) or small paid (Railway / VPS)'],
      ['C', 'Production settings: Docker image, environment variables, prod profile checks'],
      ['C', 'Deploy database, backend and frontend; Stripe webhook URL; real email (Brevo)'],
      ['C', 'Demo accounts and sample data in production; demo login buttons'],
      ['C', 'Uptime check (keeps free hosting awake during job hunting)'],
      ['C', 'Final README: GIFs, architecture + ER diagrams, k6 graph, badges, how to run'],
      ['T', '3-minute demo video (English; Tamil optional)'],
      ['T', 'Resume bullet points and LinkedIn post'],
      ['C', 'Final project guide + viva Q&A document'],
      ['C', 'Git tag v1.0'],
    ],
    output: ['Live link', 'README, demo video, resume bullets, LinkedIn post', 'Final guide + viva Q&A'],
    done: ['A friend opens the link on a phone, buys, returns, and it all works'],
    explain: ['Explain TriVoKo in 2 minutes as you would in an interview', 'Which part are you most proud of, and why?'],
    skills: 'Deployment, production configuration, documentation, presenting your work',
    where: 'hosting dashboards, `README.md`, `00_Project_Documents\\`',
  },
]
